name: Publish to CloudHub2.0
on:
  push:
    branches: [ pipeline-stages-mulesoft ]
    
jobs:         
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to CloudHub2.0
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
          -Ddecryption.key="${{ secrets.DECRYPTION_KEY }}"
